name: Debug

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: '${{ secrets.ACCESS_KEY }}'
      SECRET_KEY: '${{ secrets.SECRET_KEY }}'
    steps:
    - uses: hmarr/debug-action@v2
